fix workflow

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -57,17 +57,32 @@ jobs:
         run: |
           STATE_BUCKET=$(aws ssm get-parameter --name "/tf/global-infra/backend/state-bucket" --query "Parameter.Value" --output text --region ${{ github.event.inputs.region }})
           STATE_TABLE=$(aws ssm get-parameter --name "/tf/global-infra/backend/state-table" --query "Parameter.Value" --output text --region ${{ github.event.inputs.region }} 2>/dev/null || echo "") # ignores if not found
+          APP_TABLE=$(aws ssm get-parameter --name "/tf/global-infra/backend/app-table" --query "Parameter.Value" --output text --region ${{ github.event.inputs.region }} 2>/dev/null || echo "") # ignores if not found
           REGION=$(aws ssm get-parameter --name "/tf/global-infra/backend/region" --query "Parameter.Value" --output text --region ${{ github.event.inputs.region }})
-          echo "STATE_TABLE=$STATE_TABLE" >> $GITHUB_ENV # export for 'Disable deletion protection (Environment)' step
+          echo "STATE_TABLE=$STATE_TABLE" >> $GITHUB_ENV # export for 'Disable deletion protection (Global)' step
+          echo "APP_TABLE=$APP_TABLE" >> $GITHUB_ENV # export for 'Disable deletion protection (Environment)' step
           echo "TF_VAR_state_bucket_name=$STATE_BUCKET" >> $GITHUB_ENV
 
-          cat > ${{ env.ENVIRONMENT }}.hcl <<EOF
-          bucket         = "$STATE_BUCKET"
-          key            = "${{ env.ENVIRONMENT }}/terraform.tfstate"
-          region         = "$REGION"
-          dynamodb_table = "$STATE_TABLE"
-          encrypt        = true
-          EOF
+          # Choose which db table to use based on environment
+          if [ "$ENVIRONMENT" = "global-infra" ]; then
+            echo "Using $STATE_TABLE to destroy $ENVIRONMENT backend"
+            cat > $ENVIRONMENT.hcl <<EOF
+            bucket         = "$STATE_BUCKET"
+            key            = "$ENVIRONMENT/terraform.tfstate"
+            region         = "$REGION"
+            dynamodb_table = "$STATE_TABLE"
+            encrypt        = true
+            EOF
+          else
+            echo "Using $APP_TABLE to destroy $ENVIRONMENT backend"
+            cat > $ENVIRONMENT.hcl <<EOF
+            bucket         = "$STATE_BUCKET"
+            key            = "$ENVIRONMENT/terraform.tfstate"
+            region         = "$REGION"
+            dynamodb_table = "$APP_TABLE"
+            encrypt        = true
+            EOF
+            fi
 
       # 4. Install Terraform
       - name: Setup Terraform
@@ -79,7 +94,7 @@ jobs:
       - name: Init Terraform (Global)
         if: ${{ env.ENVIRONMENT == 'global-infra' }}
         working-directory: infrastructure/backend/global
-        run: terraform init -var-file=${{ env.ENVIRONMENT }}.tfvars
+        run: terraform init -backend-config=${{ env.ENVIRONMENT }}.hcl
 
       # 5b. Initialize Terraform on github runner
       - name: Init Terraform (Environment)
@@ -91,9 +106,7 @@ jobs:
       - name: Disable deletion protection (Global)
         if: ${{ env.ENVIRONMENT == 'global-infra' }}
         working-directory: infrastructure/backend/global
-        run: |
-          STATE_TABLE=$(grep state_table_name global-infra.tfvars | cut -d'"' -f2)-${ENVIRONMENT}
-          aws dynamodb update-table --table-name $STATE_TABLE --no-deletion-protection-enabled --region ${{ github.event.inputs.region }}
+        run: aws dynamodb update-table --table-name $STATE_TABLE --no-deletion-protection-enabled --region ${{ github.event.inputs.region }}
 
         # 6b. Disable deletion protection (if enabled)
         # - get app table from SSM Parameter Store
@@ -105,7 +118,7 @@ jobs:
       - name: Destroy (Global)
         if: ${{ env.ENVIRONMENT == 'global-infra' }}
         working-directory: infrastructure/backend/global
-        run: terraform destroy -var-file=${{ env.ENVIRONMENT }}.tfvars -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -auto-approve
+        run: terraform destroy -var="environment=${{ env.ENVIRONMENT }}" -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -auto-approve
 
       # 7b. Destroy resources
       - name: Destroy (Environment)
